task: "regression"
pred_target: "logp"
batch_size: 128
num_epoch: 10

lr: 0.001
weight_decay: 0.0
check_val_every_n_epoch: 2

save_model: True
test_only: True
resume: /home/yanming/GT-Variants-Generation/outputs/2025-03-08/zinc-regression-gtv1-19-47-13/checkpoints/regression-gtv1/last.ckpt

use_gpu: True
gpu_id: 0