task: "regression"
pred_target: "logp"
batch_size: 128
num_epoch: 250

lr: 0.0001
weight_decay: 0.0
check_val_every_n_epoch: 25

save_model: True
test_only: False
resume: null # absolute path to the checkpoint

wandb_mode: "online"
gpu_id: 1