defaults:
    - _self_
    - dataset : zinc
    - model: graph_transformer
    - run_config: regression
    - transformer_layer: gtv2

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${now:%Y-%m-%d}/${dataset.name}-${run_config.task}-${transformer_layer.type.name}-${now:%H-%M-%S}