defaults:
    - _self_
    - dataset : zinc
    - model: graph_transformer
    - run_config: train_default
    - transformer_layer: gtv1


hydra:
  job:
    chdir: True
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${dataset.name}-${run_config.task}